-- Portable SQL: PostgreSQL in the lab, H2 in PostgreSQL mode in the tests.

create table customers (
    id        bigint       primary key,
    email     varchar(120) not null,
    full_name varchar(120) not null,
    tier      varchar(16)  not null,
    country   varchar(2)   not null
);

create table products (
    id          bigint         primary key,
    sku         varchar(32)    not null,
    name        varchar(200)   not null,
    description varchar(2000)  not null,
    category    varchar(60)    not null,
    unit_price  numeric(12, 2) not null,
    stock       integer        not null,
    constraint products_sku_key unique (sku)
);

create table orders (
    id                  bigint generated by default as identity primary key,
    customer_id         bigint         not null references customers (id),
    status              varchar(20)    not null,
    confirmation_status varchar(20)    not null,
    shipping_country    varchar(2)     not null,
    total               numeric(14, 2) not null,
    created_at          timestamp with time zone not null
);

create index orders_customer_id_idx on orders (customer_id);

create table order_lines (
    id         bigint generated by default as identity primary key,
    order_id   bigint         not null references orders (id),
    product_id bigint         not null references products (id),
    quantity   integer        not null,
    unit_price numeric(12, 2) not null
);

create index order_lines_order_id_idx on order_lines (order_id);
